In [1]:
import numpy as np

In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

In [3]:
# output dataset            
y = np.array([[0,0,1,1]]).T

In [23]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [24]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [25]:
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

In [26]:
print("Output After Training:")
print(l1)
print(syn0)

Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [8]:
# forward propagation
l0 = X
l1 = nonlin(np.dot(l0,syn0))
print(l0)
print(l1)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0.009664  ]
 [0.00786466]
 [0.99358931]
 [0.99211997]]


In [9]:
# how much did we miss?
l1_error = y - l1
print(l1_error)

[[-0.009664  ]
 [-0.00786466]
 [ 0.00641069]
 [ 0.00788003]]


In [10]:
# multiply how much we missed by the 
# slope of the sigmoid at the values in l1
l1_delta = l1_error * nonlin(l1,True)
print(nonlin(l1,True))
print(l1_delta)

[[0.00957061]
 [0.00780281]
 [0.0063696 ]
 [0.00781793]]
[[-9.24903380e-05]
 [-6.13664295e-05]
 [ 4.08335433e-05]
 [ 6.16055007e-05]]


In [11]:
print(l0.T)

[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [12]:
# update weights
syn0 += np.dot(l0.T,l1_delta)
print(syn0)

[[ 9.67309547]
 [-0.20784326]
 [-4.62968811]]
