In [3]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):
    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)


Error:0.49641003190272537
Error:0.008584525653247159
Error:0.0057894598625078085
Error:0.004629176776769985
Error:0.003958765280273649
Error:0.0035101225678616766


In [4]:
np.random.seed(1)

In [5]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [6]:
# Feed forward through layers 0, 1, and 2
l0 = X
l1 = nonlin(np.dot(l0,syn0))
l2 = nonlin(np.dot(l1,syn1))

# how much did we miss the target value?
l2_error = y - l2
print(l2_error)

[[-0.47372957]
 [ 0.51104304]
 [ 0.45615914]
 [-0.54470837]]


In [14]:
# in what direction is the target value?
# were we really sure? if so, don't change too much.
l2_delta = l2_error*nonlin(l2,deriv=True)
print(l2_delta)

[[-0.11810546]
 [ 0.12769844]
 [ 0.11316304]
 [-0.13508831]]


In [11]:
print(syn0.T)

[[-0.16595599 -0.70648822 -0.20646505]
 [ 0.44064899 -0.81532281  0.07763347]
 [-0.99977125 -0.62747958 -0.16161097]
 [-0.39533485 -0.30887855  0.370439  ]]


In [13]:
print(syn1.T)

[[-0.5910955   0.75623487 -0.94522481  0.34093502]]


In [24]:
# how much did each l1 value contribute to the l2 error (according to the weights)?
l1_error = l2_delta.dot(syn1.T)
print(l1_error)

[[ 0.0698116  -0.08931546  0.11163621 -0.04026629]
 [-0.07548197  0.09657001 -0.12070373  0.04353687]
 [-0.06689016  0.08557784 -0.10696451  0.03858124]
 [ 0.07985009 -0.10215849  0.12768882 -0.04605634]]


In [10]:
# in what direction is the target l1?
# were we really sure? if so, don't change too much.
l1_delta = l1_error * nonlin(l1,deriv=True)
print(l1_delta)

[[ 0.01726822 -0.02229526  0.02772761 -0.00972897]
 [-0.0154265   0.02113446 -0.02592628  0.01087391]
 [-0.01615584  0.02001969 -0.01942197  0.00964382]
 [ 0.01511901 -0.02498445  0.01566774 -0.01119926]]


In [25]:
print(nonlin(l1,deriv=True))

[[0.24735458 0.24962369 0.2483747  0.24161584]
 [0.20437328 0.21885115 0.21479272 0.24976329]
 [0.24152793 0.23393544 0.18157393 0.24996127]
 [0.18934246 0.24456553 0.12270256 0.24316444]]


In [18]:
print(X)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [17]:
print(syn0)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]


In [27]:
print(l0.T)

[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [21]:
print(syn1)

[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [ ]:
syn1 += l1.T.dot(l2_delta)
syn0 += l0.T.dot(l1_delta)